In [1]:
import numpy as np

In [3]:
a = [1,2,3,4,5]

In [5]:
print(a)

[1, 2, 3, 4, 5]


In [7]:
print(type(a))

<class 'list'>


In [9]:
np_a = np.array(a)

In [11]:
print(np_a)

[1 2 3 4 5]


In [13]:
print(type(np_a))

<class 'numpy.ndarray'>


In [15]:
L = range(1000)
%timeit [i**2 for i in L]

166 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [19]:
a = np.arange(1000)
%timeit a**2

3.51 µs ± 62.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [23]:
a.ndim

1

In [25]:
a.shape

(4,)

In [29]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
b.ndim

2

In [37]:
b.shape

(2, 3)

In [39]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
c.ndim

3

In [43]:
c.shape

(2, 2, 2)

In [45]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [47]:
np.array(my_list)

array([1, 2, 3])

In [49]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [51]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.array(my_matrix).shape

(3, 3)

In [55]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [59]:
a = np.linspace(0, 5, 6)
a

array([0., 1., 2., 3., 4., 5.])

In [61]:
np.linspace(0,10,7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [63]:
np.zeros(3)

array([0., 0., 0.])

In [65]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [67]:
a = np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [71]:
d = np.eye(3,2)
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [73]:
a = np.diag([7, 9, 3, 4])
a

array([[7, 0, 0, 0],
       [0, 9, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [75]:
np.diag(a)

array([7, 9, 3, 4])

In [79]:
random_array = np.random.randint(1,121,5)
print(random_array)

[48 16 59 58 79]


In [81]:
a = np.random.rand(4)
a 

array([0.86276875, 0.84903175, 0.23728921, 0.26808865])

In [85]:
a = np.random.randn(100)
a

array([-2.38729412, -0.39720476,  1.07021473,  0.06371768, -0.5127332 ,
       -1.06597051,  1.16049791,  1.24265323,  0.00380642, -0.63988901,
       -1.02637248,  0.08766567, -0.48869858, -0.11576329, -0.70629232,
        0.98376759, -1.27530356,  0.42632803,  0.02720581,  1.63623501,
        2.5568813 ,  0.67393625,  0.28065359, -0.28651835, -0.32215557,
        1.14381304, -0.08932857, -1.75734012,  1.22721285,  0.05461611,
       -0.19522535,  0.09866067,  0.48730453, -0.20595579, -1.3942347 ,
        0.40329071,  0.14478056,  1.17728066, -1.89817949,  0.14923445,
       -0.23915415, -0.48987859,  0.70118844, -0.46178022,  0.35219147,
       -1.07492836, -0.84756943,  0.11189181,  0.08055162,  1.54744916,
       -1.66956918, -1.63866894, -1.58708458,  0.13119945, -1.23660921,
        1.41180104, -0.66377106, -0.41249496,  0.92478413,  1.72356678,
        0.03762885,  0.25733478, -0.06023147, -0.47955962, -1.80982421,
        1.66854727,  0.25391116, -0.09805962, -1.1235366 ,  0.90

In [87]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [89]:
arr = np.arange(25)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)


In [91]:
a1 = arr.reshape(5,5)
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [97]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print("Shape of a: {}".format(a.shape))

[[1 2 3]
 [4 5 6]]
Shape of a: (2, 3)


In [99]:
b = a.reshape(3,2)
print(b)
print("Shape of b: {}".format(b.shape))

[[1 2]
 [3 4]
 [5 6]]
Shape of b: (3, 2)


In [101]:
c = a.T
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [103]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [105]:
c.ravel()

array([1, 4, 2, 5, 3, 6])

In [107]:
a = np.array([[5, 4, 6], [2, 8, 2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 8]])

In [109]:
a = np.array([4,7,8])
a = np.append(a,[2,4,5])
print('Numpy array after addition:',a)

Numpy array after addition: [4 7 8 2 4 5]


In [113]:
a = np.delete(a,2)
print('Numpy array after deletion of one element:',a)

Numpy array after deletion of one element: [4 7 2 4 5]


In [117]:
a = np.arange(3,10)
print(a)
print(a[5])

[3 4 5 6 7 8 9]
8


In [119]:
a = np.diag([1, 2, 3])
print(a)
print(a[2,1])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
0


In [121]:
a[2,1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [123]:
a = np.arange(4,18)
a

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [125]:
a[1:8:2]

array([ 5,  7,  9, 11])

In [127]:
a = np.arange(10)
a[5:]

array([5, 6, 7, 8, 9])

In [129]:
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [131]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [133]:
b[::-1]

array([4, 3, 2, 1, 0])

In [135]:
a[5:]=b[::-1]

In [137]:
a


array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [139]:
a = np.random.randint(0, 20, 5)
a

array([13, 14,  8,  7,  3])

In [141]:
a[a % 2 ==0]

array([14,  8])

In [145]:
a[a % 2 == 0] = -1
a

array([13, -1, -1,  7,  3])

In [147]:
a = np.arange(0, 101, 10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [149]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [151]:
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200,  100])

In [153]:
a = np.array([1, 2, 3, 4])
print(a)
print(a+1)

[1 2 3 4]
[2 3 4 5]


In [155]:
a ** 2

array([ 1,  4,  9, 16])

In [157]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [159]:
a - b

array([-1.,  0.,  1.,  2.])

In [161]:
a * b

array([2., 4., 6., 8.])

In [165]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[4,4],[4,4],[4,4]])

print('Sum of a and b :\n', a+b)

Sum of a and b :
 [[ 5  6]
 [ 7  8]
 [ 9 10]]


In [167]:
print('Sum of a and b :\n', a*b)

Sum of a and b :
 [[ 4  8]
 [12 16]
 [20 24]]


In [169]:
c = np.diag([1, 2, 3, 4])
print(c * c)

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [171]:
a = np.array([[1,2,1],[3,4,3],[5,6,5]])
b = np.array([[4,4,1],[4,4,2],[4,4,3]])
print('Matrix multiplication:\n',np.matmul(a,b))

Matrix multiplication:
 [[16 16  8]
 [40 40 20]
 [64 64 32]]


In [173]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [175]:
a > b

array([False, False,  True, False])

In [177]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

In [179]:
np.array_equal(a, b)

False

In [181]:
np.array_equal(a, c)

True

In [183]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

np.logical_or(a, b)

array([ True,  True,  True, False])

In [185]:
np.logical_and(a, b)

array([ True, False, False, False])

In [187]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [189]:
np.log(a)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_3868\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [191]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [195]:
x = np.array([1, 2, 3, 4])
np.sum(x)


10

In [197]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [199]:
x.sum(axis=0)

array([3, 3])

In [201]:
x.sum(axis=1)

array([2, 4])

In [203]:
x = np.array([1, 3, 2])
x.min()

1

In [205]:
x.argmax()

1